### ISSUE TITLE
Manca il sorgente per compilare scuole.css

### ISSUE THREAD

**Issue by arturu** [italia/design-scuole-pagine-statiche#2]
Ho notato che manca il sorgente per compilare il foglio di stile "build/assets/css/scuole.css".
Gentilmente potreste pubblicare i file per poter compilare gli assets?

**Comment by arturu** [comment]
Qiesta issue mi sa che si è chiusa accidentalmente a causa del mancato merge della PR?

**Comment by zenatti-art** [comment]
La issue risulta aperta da un anno, anch'io mi trovo nella stessa situazione, il file SCSS risulta mancante, o meglio nella branch https://github.com/italia/design-scuole-pagine-statiche/tree/src-scss/src i file risultano vecchi rispetto al compilato in master.

**Comment by arturu** [comment]
> La issue risulta aperta da un anno, anch'io mi trovo nella stessa situazione, il file SCSS risulta mancante, o meglio nella branch https://github.com/italia/design-scuole-pagine-statiche/tree/src-scss/src i file risultano vecchi rispetto al compilato in master.

Forse tra 3 anni lo sapremo, visto che il ramo che citi è stato aperto 2 mesi fa giusto per caricare la cartella src...

**Comment by OProf77** [comment]
Buongiorno,
non c'è nessuna novità in merito al sorgente per compilare scuole.css ?
