### ISSUE TITLE
Da mobile l'header non funziona correttamente

### ISSUE THREAD

**Issue by theseven208** [italia/design-scuole-pagine-statiche#28]
Con l'ultima release v2.1.3 da mobile sono comparsi due problemi con l'header:
- l'header non è più sticky e non rimane fisso in alto allo scorrere della pagina;
- l'icona del cerca non è più allineata verticalmente con il div contenente hambuerger menu, logo e nome della scuola.

![immagine](https://user-images.githubusercontent.com/119845723/205605648-a9d30504-18fc-4f79-a52f-3e533c11e9bb.png)

Il problema è riproducibile anche da Chrome impostando nelle dimensioni "iPhone 12 Pro", "Pixel 5", "Samsung Galaxy S20 Ultra", mentre sembra funzionare tutto correttamente provando "iPhone SE", "iPad Air", "Surface Pro 7".

Problema riscontrato anche fisicamente da un iPhone 12 Pro Max su Safari.

**Comment by zetareticoli** [comment]
Ciao @william-ktech non riesco a riprodurre il bug, ti allego video di test in locale su v2.1.3

https://user-images.githubusercontent.com/69706/208139990-d00281ea-7a2a-4b3b-9166-07e0a73ee3b8.mov

**Comment by astagi** [comment]
@theseven208 stai provando un'istanza locale? o un sito in produzione?
