### ISSUE TITLE
L'anteprima collegata nella descrizione non è aggiornata

### ISSUE THREAD

**Issue by Fupete** [italia/design-scuole-pagine-statiche#66]
Al link https://italia.github.io/design-scuole-pagine-statiche/ (disponibile nella descrizione della repository) sembra essere disponibile una anteprima di una vecchia v2.1.3 invece della corrente v2.3.x. 

![immagine](https://github.com/italia/design-scuole-pagine-statiche/assets/6736103/43342467-a240-44af-a4c1-4744d6c0efc8)

**Comment by Fupete** [comment]
cc @zetareticoli

**Comment by astagi** [comment]
Fixed! Grazie @Fupete

**Comment by Fupete** [comment]
Sicuro @astagi? Io vedo ancora 2.1.3? È solo un tema di propagazione?

**Comment by astagi** [comment]
Ricontrollato.. Pensavo fosse solo un problema di rilascio.. Nonostante il rilascio sembra proprio che non si aggiorni :/ riapro e indago.

**Comment by Fupete** [comment]
Sarà legato alla generazione delle gh-pages? Una action da "triggerare" 🤔 ?

**Comment by Fupete** [comment]
Ah, ma non è che è hardcoded quel numero? https://github.com/italia/design-scuole-pagine-statiche/blob/ff1e05de2f5cbdfe86e1e0bfc53698d904822e36/src/index.html#L24C1-L24C19 e manca proprio l'automatismo per aggiornarlo?

**Comment by astagi** [comment]
Sistemato @Fupete
