### ISSUE TITLE
Schede Progetti

### ISSUE THREAD

**Issue by AlexDarkGraphic** [italia/design-scuole-pagine-statiche#8]
Buongiorno,
per quanto riguarda l'ordine cronologico per anni scolastici delle "schede progetti", riporta lo stesso identico problema della versione 1.0, nello specifico:

1. i progetti di anni diversi sono mischiati e non sono in ordine cronologico, mettendo in evidenza anche quelli degli anni passati.

2. Il pulsante "Consulta i progetti degli scorsi anni" non permette di filtrare i progetti tra anno in corso e anni passati, ma risultano comunque mischiati.

Grazie per l'attenzione

**Comment by zetareticoli** [comment]
Ciao,
potresti gentilmente specificare i files HTML interessati dai problemi da te esposti?
Grazie
